#
# Your Crowdin credentials
#
"project_id": "516126"
"api_token": "CROWDIN_PERSONAL_TOKEN"
"base_path": "/stfubot/lang"
"base_url": "https://api.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": false

#
# Files configuration
#
files: [
    {
      #
      # Source files filter
      # e.g. "/resources/en/*.json"
      #
      "source": "/stfubot/lang/en_US.json",

      #
      # Where translations will be placed
      # e.g. "/resources/%two_letters_code%/%original_file_name%"
      #
      "translation": "/stfubot/lang/%locale_with_underscore%.json",

      #
      # File type
      # e.g. "json"
      #
      "type": "json",
    },
  ]
