project_id: "516126"
api_token: CROWDIN_PERSONAL_TOKEN
base_path: /stfubot/lang
base_url: "https://api.crowdin.com"
preserve_hierarchy: true
files:
  - source: en_US.json
    translation: "%locale_with_underscore%.json"
    dest: "%locale_with_underscore%.json"
    type: json
